on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Install Dependencies
        run: |
          sudo Rscript -e 'install.packages("fontawesome", repos="https://cloud.r-project.org")'
          sudo Rscript -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'
          sudo Rscript -e 'install.packages("dplyr", repos="https://cloud.r-project.org")'
          sudo Rscript -e 'install.packages("stringr", repos="https://cloud.r-project.org")'
          sudo Rscript -e 'install.packages("reactable", repos="https://cloud.r-project.org")'
          sudo Rscript -e 'install.packages("htmltools", repos="https://cloud.r-project.org")'
          # sudo apt-get update
          # sudo apt-get install -y nodejs
          # npm install -g quarto
          # npm install -g quarto-render-html

      - name: Build Table
        run: quarto render index.qmd

      - name: Publish to GitHub Pages
        # uses: quarto-dev/quarto-actions/publish@v2
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          # target: gh-pages
          folder: .
          clean: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}